on:
  push:
    branches:
      - 'main'
      - 'release-[0-9]+.[0-9]+.[0-9]+' # example: release-45.2.98
      - 'releases*'
concurrency:
  group: split_monorepo-${{ github.ref_name }}-${{ github.ref }}
  cancel-in-progress: true
name: Monorepo split
jobs:
  split-branch:
    name: Split branch
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - mr-test-admin
          - mr-test-sdk
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - run: git config --global user.name "GitHub Action"
      - run: git config --global user.email "action@github.com"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Install git-filter-repo
        run: |
          sudo apt-get update
          sudo apt-get install -y git-filter-repo

      - name: Split
        run: |
          git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all
          bash ./.github/workflows/split-repositories.sh "${{ secrets.ACCESS_TOKEN }}" "${{ matrix.package }}" "${{ github.ref_name }}"
