name: Split Monorepo v2 - forcepush

on:
  workflow_dispatch:
    inputs:
      force:
        description: 'Force'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
  push:
    branches:
      - main
      - 'v[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+-prepare'
    tags:
      - '*'

concurrency:
  group: split_monorepo-${{ github.ref_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  split-branch:
    uses: peckadesign/.github/.github/workflows/split_monorepo.yaml@master
    name: Split branch
    strategy:
      fail-fast: false
      matrix:
        package:
          - mr-test-admin
          - mr-test-sdk
    with:
      package: ${{ matrix.package }}
      organization: "aloisjasa"
      force: ${{ inputs.force == 'true' }}
    secrets:
      gh-token: ${{ secrets.ACCESS_TOKEN }}
