on:
  workflow_dispatch:

concurrency:
  group: split_monorepo-${{ github.ref_name }}-${{ github.ref }}
  cancel-in-progress: true


name: Monorepo split - trigger shiw
jobs:
  split-branch:
    name: Split branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}


#    uses: AloisJasa/.github/.github/workflows/split_monorepo_git-filter.yaml@main
#    name: Split branch
#    strategy:
#      fail-fast: false
#      matrix:
#        package:
#          - mr-test-admin
##          - mr-test-sdk
#    with:
#      organization: "AloisJasa"
#      package: "mr-test-admin"
#    secrets:
#      gh-token: ${{ secrets.ACCESS_TOKEN }}

#
#
#      - run: git config --global user.name "GitHub Action"
#      - run: git config --global user.email "action@github.com"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Split
        uses: "AloisJasa/.github/.github/actions/split-monorepo@main"
        with:
          organization: "AloisJasa"
          package: "mr-test-admin"
