on:
  workflow_dispatch:

concurrency:
  group: split_monorepo-${{ github.ref_name }}-${{ github.ref }}
  cancel-in-progress: true


name: Monorepo split - trigger
jobs:
  split-branch:
    uses: AloisJasa/.github/.github/workflows/split_monorepo_git-filter.yaml@main
    name: Split branch
    strategy:
      fail-fast: false
      matrix:
        package:
          - mr-test-admin
#          - mr-test-sdk
    with:
      organization: "AloisJasa"
      package: "mr-test-admin"
    secrets:
      gh-token: ${{ secrets.ACCESS_TOKEN }}
